"""Structured Pydantic models for the 4-stage Code Grounding workflow.

These schemas map directly to the OpenProse contract 'Maintains' definitions.
"""

from typing import List, Literal
from pydantic import BaseModel, Field


class InquiryRecord(BaseModel):
    """Normalized inquiry generated by Stage 1 (Ingress)."""
    inquiry_id: str = Field(..., description="Unique inquiry identifier (e.g. INQ-001)")
    stakeholder: str = Field(default="Stakeholder", description="Name or role of the stakeholder")
    raw_question: str = Field(..., description="Original raw question")
    operational_context: str = Field(..., description="Operational background, deadlines, and impact")
    target_systems: List[str] = Field(default_factory=list, description="Target repos, services, or modules")
    stakes_severity: Literal["low", "medium", "high", "critical"] = Field(
        default="medium",
        description="Assessed risk level"
    )


class CallTree(BaseModel):
    """Call tree and mutation trace generated by Stage 2 (Discovery)."""
    entry_point: str = Field(..., description="Starting API, controller, or event trigger")
    intermediate_services: List[str] = Field(default_factory=list, description="Services traversed in forward flow")
    event_publishers: List[str] = Field(default_factory=list, description="Events emitted")
    leaf_mutations: List[str] = Field(default_factory=list, description="External side-effects or DB writes")


class PrimaryBaseline(BaseModel):
    """Primary verifiable code baseline generated by Stage 2 (Discovery)."""
    inquiry_id: str
    call_tree: CallTree
    git_intent_summary: str = Field(..., description="Summary of commit history and original author intent")
    code_citations: List[str] = Field(default_factory=list, description="Exact file:line citations")
    baseline_summary: str = Field(..., description="Synthesized initial answer based on code exploration")
    diagram_d2: str = Field(default="", description="D2 architectural diagram source code")


class Proposal(BaseModel):
    """Adversarial RFC challenge proposal generated by Stage 3."""
    proposal_id: str = Field(..., description="Unique proposal identifier (e.g. PROP-001)")
    category: Literal[
        "vacuous-predicate",
        "race-condition",
        "inactive-bypass",
        "auth-blocker",
        "intent-gap",
        "diagram-syntax"
    ] = Field(..., description="Critique category")
    target_symbol: str = Field(..., description="Specific function, symbol, or diagram affected")
    failing_scenario: str = Field(..., description="Concrete edge case or unverified path description")
    code_evidence: str = Field(..., description="Code citation or logical proof")
    suggested_revision: str = Field(..., description="Proposed correction to the baseline")


class ProposalLedger(BaseModel):
    """RFC Proposal Ledger generated by Stage 3 (Adversarial Challenge)."""
    inquiry_id: str
    proposals: List[Proposal] = Field(default_factory=list, description="List of adversarial challenge proposals")


class ReconciledVerdict(BaseModel):
    """Authoritative reconciled verdict generated by Stage 4 (Reconciliation)."""
    inquiry_id: str
    adopted_proposals: List[str] = Field(default_factory=list, description="IDs of adopted proposals")
    rejected_proposals: List[str] = Field(default_factory=list, description="IDs of rejected proposals with reasons")
    certainty_score: int = Field(..., ge=0, le=5, description="Calibrated certainty on a 0 to 5 scale")
    residual_risks: List[str] = Field(default_factory=list, description="Explicit unverified scenarios or risks")
    plain_language_verdict: str = Field(..., description="Clear executive answer for stakeholders")
    actionable_decision_matrix: str = Field(..., description="Immediate concrete actions or remediation steps")
    reconciled_diagram_d2: str = Field(default="", description="Final reconciled D2 diagram")
